### PR TITLE
added option --progress which shows a simple progress bar

### PR DESCRIPTION
**Pull request by kaplan2539**
Hey,

I added the option '--progress' or '-p' to show some progress bar on the screen while uploading large files via fel write. Hope this is useful.

Cheers
Alex

### CODE REVIEW

**Comment by ssvb** [comment]
Hi,

Usually patches are sent to the linux-sunxi mailing list with the "[PATCH sunxi-tools M/N]" prefix in the subject line. This can be done with the help of "git format-patch" and "git send-email" commands.

Regarding your patch, there are some things that might need to be fixed:
1. Inconsistent coding style. The rest of the code is using spaces to separate brackets and operators, for example we use "if (...)" instead of "if(...)".
2. The new '-p' command line option is not documented in the "help" message.
3. The '-v' and '-p' options may not be processed correctly if they are used together, depending on their order.
4. It would be probably cleaner to add a progress callback function argument to the "usb_bulk_send()" function instead of doing all the progress bar animation there directly. Because this is a low level helper function and it has a wider use than just uploading large files when handling one or more "write" command line options.

**Comment by kaplan2539** [comment]
1. OK - I'll improve that
2. OK - Will be added
3. I don't understand - according to my tests they should be processed correctly independent of their order
4. I'll do.

**Comment by ssvb** [comment]
> I don't understand - according to my tests they should be processed correctly independent
> of their order

For example, what happens if you order the command line arguments as 'fel -p -v ver' ?

**Comment by kaplan2539** [comment]
got it - whould it make sense to use getopt?

**Comment by kaplan2539** [comment]
followed your suggestions and tested a bit.
This time I sent the patch to the sunxi-linux mailing list.

**Pull request closed without merging**
