### PR TITLE
fel: Modify readl/writel functions, add "copyl"

### PR DESCRIPTION
**Pull request by n1tehawk**
The "copyl" functionality also obsoletes `fel-copy.c`, which has been removed.

### CODE REVIEW

**Comment by ssvb** [comment]
Why call it "copyl"? As for the "readl" command, the "l" suffix can be interpreted either as "long" (32-bit) or "little endian".

**Comment by n1tehawk** [comment]
I wanted it to be the same as "readl"/"writel" in the sense of 'long'. 'Little endian' doesn't apply, as this is not a copy between (USB) host and target device, but within SoC memory - so it's always 'native' endianness.

The 'long' is to hint that this command transfers 32-bit words, contrary to a 'string' (= byte-oriented) copy.

Can you suggest a better name?

**Comment by ssvb** [comment]
If we want to have this functionality implemented, then I would rather have a more generic "memmove" command. With byte granularity for the buffer size. And also with a proper handling of the overlapped buffers.

**Comment by n1tehawk** [comment]
My goal / "use case" initially was to eliminate the need for `fel-copy.c` (see #78).

I can also imagine that this copy function (once factored out into a FEL/USB "library") eventually gets used in a refreshed _sunxi-pio_, which would gain the ability to access the PIO registers more directly, instead of taking the "`fel-pio.bin` + file access" route. Accessing hardware registers is where the 'long' approach matters, see the source comment in 9a03f17.

**Comment by ssvb** [comment]
I think that we can just drop ``fel-copy.c`` without bothering to provide any replacement. As for the ``sunxi-pio`` functionality, it would be best to have it just integrated as a high level command of the ``sunxi-fel`` tool.

**Pull request closed without merging**
