### PR TITLE
Fixes and adding a "Github Actions" file to replace broken Travis CI

### PR DESCRIPTION
**Pull request by apritzel**
Some fixes for issues I stumbled upon:
- GCC 11 issues a warning for some wrongly annotated parameter.
- The FEX compiler cannot deal with '-' and '/' characters in section and key names. This is replacing PR #103, which had an issue that I fixed.
- make check is broken, due to changes in mainline sunix-boards.git HEAD, which it downloads. I issued [PR 70](https://github.com/linux-sunxi/sunxi-boards/pull/70) **there**, but meanwhile carry a patch applied to the downloaded zip file. This can hopefully removed soon.
- Travis CI seems to be broken (in technical and administrative ways), see the commit message. Replace it with a Github Actions file to get some CI coverage back.

Please merge, and consider making a v1.5 release.

### CODE REVIEW

**Comment by apritzel** [comment]
@ijc can you have a look at this? Did you encounter other issues or have more patches/fixes up your sleeves?
If not, can we get a new release (v1.5) done? If yes, how, exactly?

**Comment by ijc** [comment]
> @ijc can you have a look at this? 

The first two code changes look fine to me. :+1:

I'm afraid I'm not qualified to give :+1:/:-1: to the semantic meaning of "fex: add support for '-' and '/' characters", the code looks ok but is there a reason why one place allows `-` and `/` and the other only `-`?

Is there a PR open to fix the fex files at source? If not then there should be and I would suggest linking to it in the header of the comment (or even adjusting BOARDS_URL to just use it...)

I've never used GHA and haven't read the docs but the file looks pretty standard so :+1: on that assuming it builds. I suppose we don't want to run it on PRs for security reasons? Are there mechanisms to allow "wait for admin approval" which could be used for PRs?

I note that changes to sunxi-boards will now potentially break the master CI in this repo in an asynchronous way, is that what we want? Might it be better to point to a specific commit and bump occasionally, or to move these tests to that repo so they catch the bugs as they are introduced?

> Did you encounter other issues or have more patches/fixes up your sleeves?

The diff in the debian package is currently just:
```diff
$ git diff upstream/master -- . ':!debian'
diff --git a/tests/Makefile b/tests/Makefile
index f3560a3..7822ab5 100644
--- a/tests/Makefile
+++ b/tests/Makefile
@@ -5,7 +5,7 @@
 BOARDS_URL := https://github.com/linux-sunxi/sunxi-boards/archive/master.zip
 BOARDS_DIR := sunxi-boards
 
-check: check_all_fex coverage
+check: coverage
 
 # Conversion cycle (.fex -> .bin -> .fex) test for all sunxi-boards
 check_all_fex: $(BOARDS_DIR)/README unify-fex
diff --git a/tests/test_bin2fex_corner_cases.sh b/tests/test_bin2fex_corner_cases.sh
index b10746b..6296606 100755
--- a/tests/test_bin2fex_corner_cases.sh
+++ b/tests/test_bin2fex_corner_cases.sh
@@ -7,6 +7,11 @@ TESTFILE=sunxi-boards/sys_config/a10/a10-olinuxino-lime
 # use sunxi-fexc in "fex2bin" mode, testing explicit parameters at the same time
 FEX2BIN="../sunxi-fexc -v -q -I fex -O bin"
 
+if [ ! -e "${TESTFILE}" } ; then
+    echo >&2 "Skipping $(basename $0), no board files found"
+    exit 0
+fi
+
 ${FEX2BIN} ${TESTFILE}.fex ${TESTFILE}.bin
 # have bin2fex explicitly read /dev/stdin, to force use of fexc.c's "read_all()"
 cat ${TESTFILE}.bin | ${BIN2FEX} /dev/stdin > /dev/null
```

Which are due to the download of https://github.com/linux-sunxi/sunxi-boards/archive/master.zip, network access during build is not permitted by Debian Policy. I don't think the missing tests are terribly important in the context of a package build (especially if upstream CI is already going to do them) and I think the diff is not one upstream would want.

> If not, can we get a new release (v1.5) done? If yes, how, exactly?

I've no idea who even has the perms, is it more complicated than pushing a tag and attaching some tarballs to a release? I see 1.4 was done as a ["release"](https://github.com/linux-sunxi/sunxi-tools/releases) but 1.4.1 and 1.4.2 were only [tagged]
(https://github.com/linux-sunxi/sunxi-tools/tags). If you don't have the necessary GH perms perhaps @wens does since they have been merging things?

**Comment by apritzel** [comment]
> The first two code changes look fine to me. +1

Thanks!

> I'm afraid I'm not qualified to give +1/-1 to the semantic meaning of "fex: add support for '-' and '/' characters", the code looks ok but is there a reason why one place allows `-` and `/` and the other only `-`?

This was due to @plaes response to PR #103, where he stated that we should not allow slashes in key names, but they are fine in section names, to which I agree.

> Is there a PR open to fix the fex files at source? If not then there should be and I would suggest linking to it in the header of the comment (or even adjusting BOARDS_URL to just use it...)

I mentioned that in the message above, it's PR 70 there, but Github makes links to PRs in other repos more a second class citizen.

> I've never used GHA and haven't read the docs but the file looks pretty standard so +1 on that assuming it builds. I suppose we don't want to run it on PRs for security reasons? Are there mechanisms to allow "wait for admin approval" which could be used for PRs?

I learned about GHA less than 24 hours ago as well ;-)
From what I gathered, running CI jobs on every PR seems standard, and the security concerns do not affect us, but are more in GH's responsibility, since it's their infrastructure. So I just kept the standard "on every PR targeting master and every merge into master", as the template suggested.

> I note that changes to sunxi-boards will now potentially break the master CI in this repo in an asynchronous way, is that what we want? Might it be better to point to a specific commit and bump occasionally, or to move these tests to that repo so they catch the bugs as they are introduced?

I don't know for sure, but that's what it always was (pulling current master), so I suppose trying new files is intended. There is a (now also defunct) Travis-CI job for sunxi-boards as well, which does the same: pulling sunxi-tools and running "make check", so ideally new issues should be caught early - assuming they would work.
TBH I don't really care about this FEX crap, I just wanted to keep the checks alive and somewhat meaningful - so not sure we should boil the ocean here.

> > Did you encounter other issues or have more patches/fixes up your sleeves?
> 
> The diff in the debian package is currently just:
> 
> ```diff
> $ git diff upstream/master -- . ':!debian'
> diff --git a/tests/Makefile b/tests/Makefile
> index f3560a3..7822ab5 100644
> --- a/tests/Makefile
> +++ b/tests/Makefile
> @@ -5,7 +5,7 @@
>  BOARDS_URL := https://github.com/linux-sunxi/sunxi-boards/archive/master.zip
>  BOARDS_DIR := sunxi-boards
>  
> -check: check_all_fex coverage
> +check: coverage
>  
>  # Conversion cycle (.fex -> .bin -> .fex) test for all sunxi-boards
>  check_all_fex: $(BOARDS_DIR)/README unify-fex
> diff --git a/tests/test_bin2fex_corner_cases.sh b/tests/test_bin2fex_corner_cases.sh
> index b10746b..6296606 100755
> --- a/tests/test_bin2fex_corner_cases.sh
> +++ b/tests/test_bin2fex_corner_cases.sh
> @@ -7,6 +7,11 @@ TESTFILE=sunxi-boards/sys_config/a10/a10-olinuxino-lime
>  # use sunxi-fexc in "fex2bin" mode, testing explicit parameters at the same time
>  FEX2BIN="../sunxi-fexc -v -q -I fex -O bin"
>  
> +if [ ! -e "${TESTFILE}" } ; then
> +    echo >&2 "Skipping $(basename $0), no board files found"
> +    exit 0
> +fi
> +
>  ${FEX2BIN} ${TESTFILE}.fex ${TESTFILE}.bin
>  # have bin2fex explicitly read /dev/stdin, to force use of fexc.c's "read_all()"
>  cat ${TESTFILE}.bin | ${BIN2FEX} /dev/stdin > /dev/null
> ```
> 
> Which are due to the download of https://github.com/linux-sunxi/sunxi-boards/archive/master.zip, network access during build is not permitted by Debian Policy. I don't think the missing tests are terribly important in the context of a package build (especially if upstream CI is already going to do them) and I think the diff is not one upstream would want.

Yeah, I agree. We could think about adding some kind of "nasty.fex example" directly into the repo, combining some properties that we would like to test against (like those slashes), so there would be at least some test.

> > If not, can we get a new release (v1.5) done? If yes, how, exactly?
> 
> I've no idea who even has the perms, is it more complicated than pushing a tag and attaching some tarballs to a release? I see 1.4 was done as a ["release"](https://github.com/linux-sunxi/sunxi-tools/releases) but 1.4.1 and 1.4.2 were only [tagged] (https://github.com/linux-sunxi/sunxi-tools/tags). If you don't have the necessary GH perms perhaps @wens does since they have been merging things?

Yeah, I don't know either, but I am tempted to just do a PR with a tag, given there are no issues left.
I can go and sneak into other distro's packages to see if they carry out-of-tree patches.

Thanks for your time!

**Comment by ijc** [comment]
> > I'm afraid I'm not qualified to give +1/-1 to the semantic meaning of "fex: add support for '-' and '/' characters", the code looks ok but is there a reason why one place allows - and / and the other only -?

> This was due to @plaes response to PR https://github.com/linux-sunxi/sunxi-tools/pull/103, where he stated that we should not allow slashes in key names, but they are fine in section names, to which I agree.

Thanks, it makes sense but in that case then I found the commit message confusing when it said "Relax the section and key filter to allow '-' and '/' as well." which seems to conflict with that has been changed.

> >  Is there a PR open to fix the fex files at source? If not then there should be and I would suggest linking to it in the header of the comment (or even adjusting BOARDS_URL to just use it...)
> I mentioned that in the message above, it's PR 70 there,

Sorry, I was just reading the commit message and didn't think to look back to the PR intro. I think it would be worth adding a link to the commit or patch itself though?

>  but Github makes links to PRs in other repos more a second class citizen.

FWIW if you just put the full URL `https://github.com/linux-sunxi/sunxi-boards/pull/70` then GH magically renders it as https://github.com/linux-sunxi/sunxi-boards/pull/70.

>  So I just kept the standard "on every PR targeting master and every merge into master", as the template suggested.

Ah, thanks, I just hadn't groked what `pull_request:     branches: [ master ]` meant and I suppose it means "PRs _targetting_ master" which sounds good.

> TBH I don't really care about this FEX crap, I just wanted to keep the checks alive and somewhat meaningful - so not sure we should boil the ocean here.

Fair.

> Yeah, I don't know either, but I am tempted to just do a PR with a tag, given there are no issues left.

I didn't know one could PR a tag....

> Did you encounter other issues or have more patches/fixes up your sleeves?

I did just make https://github.com/linux-sunxi/sunxi-tools/pull/172 but it's not a blocker for a release IMHO.

**Comment by apritzel** [comment]
This updated PR adds a patch to explictly deal with a trailing semicolon, both in the FEX parser, but also in the unfiy_fex tools that prettifies the .fex files for the comparisons in "make check".
The patch to fix up the .fex files imported from sunxi-boards got amended to not strip off the semicolon there, since the parser can now handle it.
I also updated the PR over at sunxi-boards, if that is taken soon enough, this "checks: ..." patch can be further trimmed.

**Comment by apritzel** [comment]
So this is what the CI run looks like, on the master branch in my repo: https://github.com/apritzel/sunxi-tools/actions/runs/1895584755.
That shows that it runs make check and all tests pass.

**Comment by apritzel** [comment]
Hi,
@amery @rzk @hno @wingrime @rellla @oliv3r @paulkocialkowski
does anyone still care about sunxi-tools? The top three PRs (#164, #171, #173) are lingering around for a while now and should be good to go. Especially #171 fixes things and allows to close issues, so I would really appreciate if someone would merge them.
And apart from those particular PRs, how is this going to be handled in the future? Many thanks to @wens for merging stuff in the past, but I wonder if this becomes a bottleneck?

**Comment by amery** [comment]
I haven't been involved in years, it wouldn't be right for me to step back from the shadows and blindly merge it just to disappear again

**Comment by apritzel** [comment]
thanks @amery. Sure, that's fine and expected, part of this exercise is to find out who is still interested. I totally understand that people move on.

**Comment by ssvb** [comment]
@apritzel A better question is: would you prefer to merge such PRs yourself? I can see that somebody tried to invite you as a linux-sunxi github project member at some point in the past, but this invitation expired:
apritzel-invite

**Comment by apritzel** [comment]
Yeah, that was libv, but for something else that actually didn't really need membership, so I didn't react on it.
But yeah, membership would probably be beneficial to be able to merge PRs more quickly. So if people agree, I would be happy to accept this time.

**Comment by oliv3r** [comment]
I'm not that active on github where I can avoid it, and only use gitlab :) so I often miss these kind of notifications, unless explicitly pinged :)

**Comment by ssvb** [comment]
> So if people agree, I would be happy to accept this time.

I have refreshed the invitation and looks like now you are in. I guess, "how is this going to be handled in the future?" is resolved now.

**Comment by apritzel** [comment]
@ssvb many thanks for that, I used the opportunity to close some issues already. Unfortunately it solves only part of that "future" problem, as I dislike to merge my own PRs ... ;-)

**Comment by ssvb** [comment]
Yes, running a one-man show isn't very fun. Having competent reviewers for pull requests is surely much better. But as you see it yourself, many people are not active anymore and are only nominally counted as linux-sunxi project members nowadays.

**Pull request merged**
